### ISSUE TITLE
GraphQL Server?

### ISSUE THREAD

**Issue by mikejmets** [Richard87/test-apollo-form#2]
Hi, I have the app up and I get the Todo Form with a domain field and Close and Save buttons. But adding a domain and clicking Save does nothing. I presume I need a graphql server but I don't see any mention on how to set that up. I've found graphql tutorials but none that are related to domains. What am I missing?

**Comment by Richard87** [comment]
Hi! 

Yeah, this project is just to illustrate a bug I found with react-apollo-form, and uses a test GraphQL server at work. Unfortunatly I can't publish that source code now...
